//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdelantoSet
    {
        public int Id { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Conductor_Id { get; set; }
        public int Administrador_Id { get; set; }
    
        public virtual ConductorSet ConductorSet { get; set; }
        public virtual AdministradorSet AdministradorSet { get; set; }
    }
}
