//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanciaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistanciaSet()
        {
            this.ViajeSet = new HashSet<ViajeSet>();
        }
    
        public int Id { get; set; }
        public short DistanciaKm { get; set; }
        public int Ingenio_Id { get; set; }
        public int Finca_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViajeSet> ViajeSet { get; set; }
        public virtual FincaSet FincaSet { get; set; }
        public virtual IngenioSet IngenioSet { get; set; }
    }
}
