//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajeSet
    {
        public int Id { get; set; }
        public decimal Peso { get; set; }
        public decimal Fecha { get; set; }
        public bool Estado { get; set; }
        public int Distancia_Id { get; set; }
        public int Conductor_Id { get; set; }
        public int Camion_Id { get; set; }
    
        public virtual CamionSet CamionSet { get; set; }
        public virtual ConductorSet ConductorSet { get; set; }
        public virtual DistanciaSet DistanciaSet { get; set; }
    }
}
